import { ImageSourcePropType } from 'react-native';

export const SignAssets: Record<string, ImageSourcePropType> = {
  '30_end': require('../signs/30 end.png'),
  '30_max': require('../signs/30 max.png'),
  '30km': require('../signs/30km.png'),
  'crossroads': require('../signs/Crossroads.png'),
  'give_way': require('../signs/Give way.png'),
  'level_crossing_barrier': require('../signs/Level crossing with barrier.png'),
  'mini_roundabout': require('../signs/Mini Roundabout.png'),
  'no_entry': require('../signs/No entry sign.png'),
  'no_right_turn': require('../signs/No-right-turn sign.png'),
  'oncoming_traffic': require('../signs/Oncoming Traffic.png'),
  'parking_verge': require('../signs/Parking on verge.png'),
  'parking_verge2': require('../signs/Parking on verge2.png'),
  'parking_zone': require('../signs/ParkingZone.png'),
  'stop_police': require('../signs/STOP POLICE.png'),
  'turn_right_mandatory': require('../signs/Turn-right mandatory sign.png'),
  'two_way_crosses_one_way': require('../signs/Two-way traffic crosses one-way road.png'),
  'two_way_straight_ahead': require('../signs/Two-way traffic straight ahead.png'),
  'u_turn': require('../signs/U turn.png'),
  'ahead_only': require('../signs/ahead only.png'),
  'bump': require('../signs/bump.png'),
  'children_crossing': require('../signs/children crossing.png'),
  'cyclist2': require('../signs/cyclist2.png'),
  'cyclist3': require('../signs/cyclist3.png'),
  'cyclists_ahead': require('../signs/cyclists ahead.png'),
  'double_bend': require('../signs/double ben.png'),
  'end_30': require('../signs/end 30.png'),
  'end_of_dual_carriage': require('../signs/end of dual carriage.png'),
  'end_of_no_overtaking': require('../signs/end of no overtaking.png'),
  'image1': require('../signs/image1.png'),
  'image2': require('../signs/image2.png'),
  'image4': require('../signs/image4.png'),
  'keep_left': require('../signs/keep left.png'),
  'lane_ends_merge': require('../signs/lane ends merge.png'),
  'mandatory_u': require('../signs/mandatory u.png'),
  'max_speed': require('../signs/max speed.png'),
  'narrow_road': require('../signs/narrow road.png'),
  'no_cycling': require('../signs/no cycling.png'),
  'no_overtaking': require('../signs/no overtaking.png'),
  'no_parking': require('../signs/no parking.png'),
  'no_pedestrians': require('../signs/no pedestrians.png'),
  'no_stopping': require('../signs/no stopping.png'),
  'no_u_turn': require('../signs/no u turn.png'),
  'no_vehicles': require('../signs/no vehicles.png'),
  'one_way': require('../signs/one way.png'),
  'parkraw': require('../signs/parkraw.png'),
  'pedestrian': require('../signs/pedestrian.png'),
  'pedestrian2': require('../signs/pedestrian2.png'),
  'recommended_speed': require('../signs/recommended speed.png'),
  'right': require('../signs/right.png'),
  'road_narrows_both_ends': require('../signs/road narrows on booth ends.png'),
  'roundabout_ahead': require('../signs/roundabout ahead.png'),
  'sharp_bend_right': require('../signs/sharp bend to the right.png'),
  'staggered_junction': require('../signs/staggered junction.png'),
  'stop_police2': require('../signs/stop poloce2.png'),
  'stop': require('../signs/stop.png'),
  'tjunction': require('../signs/tjunction.png'),
  'turn_left_ahead': require('../signs/turn left ahead.png'),
  'turn_left': require('../signs/turn left.png'),
  'uneven_surface': require('../signs/uneven surface.png'),
  'without_a_gate': require('../signs/without a gate.png'),
};

/**
 * Common sign pair mappings for quiz pair IDs
 */
export const SignPairs: Record<string, { A: ImageSourcePropType; B: ImageSourcePropType; nameA?: string; nameB?: string }> = {
  'A1': {
    A: SignAssets['give_way'],
    B: SignAssets['stop'],
    nameA: 'Give Way',
    nameB: 'Stop',
  },
  'B1': {
    A: SignAssets['pedestrian'],
    B: SignAssets['children_crossing'],
    nameA: 'Pedestrian Crossing',
    nameB: 'Children Crossing',
  },
  'B2': {
    A: SignAssets['pedestrian2'],
    B: SignAssets['no_pedestrians'],
    nameA: 'Pedestrian Walkway',
    nameB: 'No Pedestrians',
  },
  'B3': {
    A: SignAssets['cyclists_ahead'],
    B: SignAssets['no_cycling'],
    nameA: 'Cyclists Ahead',
    nameB: 'No Cycling',
  },
  'B4': {
    A: SignAssets['level_crossing_barrier'],
    B: SignAssets['without_a_gate'],
    nameA: 'Level Crossing with Barrier',
    nameB: 'Level Crossing without Gate',
  },
  'B5': {
    A: SignAssets['roundabout_ahead'],
    B: SignAssets['mini_roundabout'],
    nameA: 'Roundabout Ahead',
    nameB: 'Mini Roundabout',
  },
  'B6': {
    A: SignAssets['bump'],
    B: SignAssets['uneven_surface'],
    nameA: 'Speed Bump',
    nameB: 'Uneven Surface',
  },
  'C1': {
    A: SignAssets['no_entry'],
    B: SignAssets['no_vehicles'],
    nameA: 'No Entry',
    nameB: 'No Vehicles',
  },
  'C2': {
    A: SignAssets['no_parking'],
    B: SignAssets['no_stopping'],
    nameA: 'No Parking',
    nameB: 'No Stopping',
  },
  'C3': {
    A: SignAssets['no_u_turn'],
    B: SignAssets['mandatory_u'],
    nameA: 'No U-Turn',
    nameB: 'Mandatory U-Turn',
  },
  'C4': {
    A: SignAssets['no_overtaking'],
    B: SignAssets['end_of_no_overtaking'],
    nameA: 'No Overtaking',
    nameB: 'End of No Overtaking',
  },
  'C5': {
    A: SignAssets['turn_left'],
    B: SignAssets['turn_left_ahead'],
    nameA: 'Turn Left',
    nameB: 'Turn Left Ahead',
  },
  'C6': {
    A: SignAssets['turn_right_mandatory'],
    B: SignAssets['no_right_turn'],
    nameA: 'Turn Right Mandatory',
    nameB: 'No Right Turn',
  },
  'D1': {
    A: SignAssets['30_max'],
    B: SignAssets['30_end'],
    nameA: 'Maximum Speed 30',
    nameB: 'End of 30 Speed Limit',
  },
  'D2': {
    A: SignAssets['max_speed'],
    B: SignAssets['recommended_speed'],
    nameA: 'Max Speed',
    nameB: 'Recommended Speed',
  },
  'D3': {
    A: SignAssets['one_way'],
    B: SignAssets['two_way_traffic_crosses_one_way'] || SignAssets['two_way_crosses_one_way'],
    nameA: 'One Way',
    nameB: 'Two-Way Traffic',
  },
  'D4': {
    A: SignAssets['end_of_dual_carriage'],
    B: SignAssets['two_way_straight_ahead'],
    nameA: 'End of Dual Carriageway',
    nameB: 'Two-Way Traffic Straight Ahead',
  },
  'D5': {
    A: SignAssets['narrow_road'],
    B: SignAssets['road_narrows_both_ends'],
    nameA: 'Narrow Road Ahead',
    nameB: 'Road Narrows on Both Sides',
  },
  'D6': {
    A: SignAssets['crossroads'],
    B: SignAssets['staggered_junction'],
    nameA: 'Crossroads',
    nameB: 'Staggered Junction',
  },
  'E1': {
    A: SignAssets['sharp_bend_right'],
    B: SignAssets['double_bend'],
    nameA: 'Sharp Bend Right',
    nameB: 'Double Bend',
  },
  'E2': {
    A: SignAssets['parking_zone'],
    B: SignAssets['parking_verge'],
    nameA: 'Parking Zone',
    nameB: 'Parking on Verge',
  },
  'E3': {
    A: SignAssets['stop_police'],
    B: SignAssets['stop_police2'],
    nameA: 'Stop Police',
    nameB: 'Stop Police Checkpoint',
  },
  'E4': {
    A: SignAssets['lane_ends_merge'],
    B: SignAssets['keep_left'],
    nameA: 'Lane Ends Merge',
    nameB: 'Keep Left',
  },
};
